syntax on
set hidden
set title
set ruler
set hlsearch
set incsearch
set expandtab
set smartindent
set shiftwidth=2
set tabstop=4
set softtabstop=2

" 4-space tab widths for python (and pyrex)
autocmd FileType py* setlocal shiftwidth=4 tabstop=8 softtabstop=4

" highlight lines over 79 cols, spaces at the end of lines and tab characters
highlight BadStyle ctermbg=darkblue ctermfg=green
match BadStyle "\(\%>79v.\+\|\t\| \+$\)"

" # key toggle comments in python
function! TogglePythonComments()
 if match(getline("."), '^ *#') >= 0
   execute ':s+#++' |
 else
   execute ':s+^+#+' |
 endif
endfunction
autocmd FileType python map # :call TogglePythonComments()<cr>
map <C-n> :bn<cr>
map <C-p> :bp<cr>
map <C-t> :E<cr>
" Generated by Color Theme Generator at Sweyla
" http://themes.sweyla.com/seed/950656/

set background=dark

hi clear

if exists("syntax_on")
  syntax reset
endif

" Set environment to 256 colours
set t_Co=256

let colors_name = "sweyla950656"

if version >= 700
  hi CursorLine     guibg=#000404 ctermbg=16
  hi CursorColumn   guibg=#000404 ctermbg=16
  hi MatchParen     guifg=#A2D0FF guibg=#000404 gui=bold ctermfg=153 ctermbg=16 cterm=bold
  hi Pmenu          guifg=#FFFFFF guibg=#323232 ctermfg=255 ctermbg=236
  hi PmenuSel       guifg=#FFFFFF guibg=#FF7882 ctermfg=255 ctermbg=210
endif

" Background and menu colors
hi Cursor           guifg=NONE guibg=#FFFFFF ctermbg=255 gui=none
hi Normal           guifg=#FFFFFF guibg=#000404 gui=none ctermfg=255 ctermbg=16 cterm=none
hi NonText          guifg=#FFFFFF guibg=#0F1313 gui=none ctermfg=255 ctermbg=233 cterm=none
hi LineNr           guifg=#FFFFFF guibg=#191D1D gui=none ctermfg=255 ctermbg=234 cterm=none
hi StatusLine       guifg=#FFFFFF guibg=#331B1D gui=italic ctermfg=255 ctermbg=234 cterm=italic
hi StatusLineNC     guifg=#FFFFFF guibg=#282C2C gui=none ctermfg=255 ctermbg=235 cterm=none
hi VertSplit        guifg=#FFFFFF guibg=#191D1D gui=none ctermfg=255 ctermbg=234 cterm=none
hi Folded           guifg=#FFFFFF guibg=#000404 gui=none ctermfg=255 ctermbg=16 cterm=none
hi Title            guifg=#FF7882 guibg=NONE    gui=bold ctermfg=210 ctermbg=NONE cterm=bold
hi Visual           guifg=#FF88B2 guibg=#323232 gui=none ctermfg=211 ctermbg=236 cterm=none
hi SpecialKey       guifg=#E01F64 guibg=#0F1313 gui=none ctermfg=161 ctermbg=233 cterm=none
"hi DiffChange       guibg=#4C4F02 gui=none ctermbg=58 cterm=none
"hi DiffAdd          guibg=#25284F gui=none ctermbg=235 cterm=none
"hi DiffText         guibg=#663468 gui=none ctermbg=241 cterm=none
"hi DiffDelete       guibg=#3F0303 gui=none ctermbg=52 cterm=none
 
hi DiffChange       guibg=#4C4C09 gui=none ctermbg=234 cterm=none
hi DiffAdd          guibg=#252556 gui=none ctermbg=17 cterm=none
hi DiffText         guibg=#66326E gui=none ctermbg=22 cterm=none
hi DiffDelete       guibg=#3F000A gui=none ctermbg=0 ctermfg=196 cterm=none
hi TabLineFill      guibg=#5E5E5E gui=none ctermbg=235 ctermfg=228 cterm=none
hi TabLineSel       guifg=#FFFFD7 gui=bold ctermfg=230 cterm=bold


" Syntax highlighting
hi Comment guifg=#FF7882 gui=none ctermfg=210 cterm=none
hi Constant guifg=#E01F64 gui=none ctermfg=161 cterm=none
hi Number guifg=#E01F64 gui=none ctermfg=161 cterm=none
hi Identifier guifg=#DEFF9F gui=none ctermfg=193 cterm=none
hi Statement guifg=#A2D0FF gui=none ctermfg=153 cterm=none
hi Function guifg=#47E1FC gui=none ctermfg=81 cterm=none
hi Special guifg=#3AFF5B gui=none ctermfg=83 cterm=none
hi PreProc guifg=#3AFF5B gui=none ctermfg=83 cterm=none
hi Keyword guifg=#A2D0FF gui=none ctermfg=153 cterm=none
hi String guifg=#FF88B2 gui=none ctermfg=211 cterm=none
hi Type guifg=#53EA9A gui=none ctermfg=78 cterm=none
hi pythonBuiltin guifg=#DEFF9F gui=none ctermfg=193 cterm=none
hi TabLineFill guifg=#663849 gui=none ctermfg=238 cterm=none

